{% set name = "frugally-deep" %}
{% set version = "0.15.28" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Dobiasd/{{ name }}/archive/refs/tags/v{{ version }}-p0.tar.gz
  sha256: cad9d8932e4da90d800ed78f614a8f93e4e106aa27b81c7e3049bb8223db5572

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [not win]
    - cmake

  host:
    - functionalplus
    - eigen
    - nlohmann_json

test:
  commands:
    - test -f ${PREFIX}/include/fdeep/tensor_shape.hpp  # [not win]
    - test -f ${PREFIX}/lib/cmake/frugally-deep/frugally-deepConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\fdeep\\tensor_shape.hpp exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\frugally-deep\\frugally-deepConfig.cmake exit 1  # [win]

about:
  home: https://github.com/Dobiasd/frugally-deep
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Header-only library for using Keras (TensorFlow) models in C++.

extra:
  recipe-maintainers:
    - GiulioRomualdi
    - traversaro
